Repository co-KKIRI/FE_co-KKIRI, pull requests merged in 2024-03, with the labels that each got.

#13 Feat: Chip 컴포넌트 UI 구현
  co-kkiri/src/components/commons/Chips/DefaultChip.tsx
  co-kkiri/src/components/commons/Chips/PositionChip.tsx
  co-kkiri/src/components/commons/Chips/ProjectChip.tsx
Labels: enhancement

#22 Feat: home, study list 페이지에 사용되는 카드 컴포넌트 제작
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Card/Count.tsx
  co-kkiri/src/components/commons/Card/Header.tsx
  co-kkiri/src/components/commons/Card/Positions.tsx
  co-kkiri/src/components/commons/Card/Scrap.tsx
  co-kkiri/src/components/commons/Card/Stacks.tsx
  co-kkiri/src/components/commons/Card/Title.tsx
  co-kkiri/src/components/commons/Card/index.tsx
Labels: enhancement

#34 Feat: VariantStyle 제네릭 타입 구현
  co-kkiri/src/types/styledUtilTypes.ts
Labels: enhancement

#41 Refactor: Card, Stacks, Position 컴포넌트 수정
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Card/Title.tsx
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/components/modals/UserProfileModal/index.tsx
  co-kkiri/src/components/modals/UserProfileModal/test.tsx
Labels: refactor

#44 Feat: navigation layout 구현
  co-kkiri/index.html
  co-kkiri/src/PageRouter.tsx
  co-kkiri/src/components/commons/Gnb/Gnb.styled.ts
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/commons/SideBar/SideBar.styled.ts
  co-kkiri/src/components/commons/SideBar/index.tsx
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/components/modals/AuthModal.tsx
  co-kkiri/src/components/modals/ModalLayout.tsx
  co-kkiri/src/layouts/Navigation.tsx
Labels: enhancement

#45 Feat: ConfirmModal 컴포넌트 UI 구현
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/constants/modal.ts
Labels: enhancement

#48 Feature/issue 39 feat default chip 확장 및 추가 chip
  co-kkiri/src/components/commons/Chips/DefaultChip.tsx
  co-kkiri/src/components/commons/Chips/DeleteStackChip.tsx
  co-kkiri/src/components/commons/Chips/ProjectChip.tsx
  co-kkiri/src/components/commons/Chips/SelectPositionChip.tsx
  co-kkiri/src/components/commons/Chips/StackChip.tsx
  co-kkiri/src/styles/tokens.ts
Labels: enhancement

#52 Feat: FilterDropdownButton 구현
  co-kkiri/src/components/commons/DropdownButton.tsx
  co-kkiri/src/components/commons/DropdownMenu.tsx
  co-kkiri/src/components/commons/PopoverButton.tsx
  co-kkiri/src/components/commons/SelectDropOptions/FilterDropdownButton.tsx
  co-kkiri/src/components/commons/SelectDropOptions/SortSelectButton.tsx
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/hooks/.gitkeep
  co-kkiri/src/hooks/useOpenToggle.ts
Labels: enhancement

#53 Fix: 모달포탈 스크롤 고치기
  co-kkiri/src/components/modals/ModalLayout.tsx
Labels: bug

#56 Feat: 상세 페이지 요약 카드 구현
  co-kkiri/src/components/domains/.gitkeep
  co-kkiri/src/components/domains/ProjectDetailCard/ProjectDetailRow.tsx
  co-kkiri/src/components/domains/ProjectDetailCard/ProjectDetailTable.tsx
  co-kkiri/src/components/domains/ProjectDetailCard/index.tsx
  co-kkiri/src/components/domains/ProjectDetailCard/types.ts
  co-kkiri/src/types/ObjectUtilTypes.ts
Labels: enhancement

#60 Feat: category 컴포넌트 구현
  co-kkiri/package-lock.json
  co-kkiri/src/assets/icons/category_selected.svg
  co-kkiri/src/components/commons/Category.tsx
  co-kkiri/src/constants/icons.ts
Labels: enhancement

#62 Feat: Comment 컴포넌트 추가 구현
  co-kkiri/src/components/commons/Comment.tsx
  co-kkiri/src/components/commons/Comment/Comment.styled.ts
  co-kkiri/src/components/commons/Comment/Comment.tsx
  co-kkiri/src/components/commons/CommentInput.tsx
  co-kkiri/src/components/commons/FilterButton.tsx
  co-kkiri/src/components/commons/SelectDropOptions/FilterDropdownButton.tsx
Labels: enhancement

#63 Feat: home 페이지 구현
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/commons/Scrap.tsx
  co-kkiri/src/components/commons/Stack.tsx
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/components/domains/home/Banner.tsx
  co-kkiri/src/components/domains/home/Banners.tsx
  co-kkiri/src/components/domains/home/Cards.tsx
  co-kkiri/src/components/domains/home/HotAndNewSection.tsx
  co-kkiri/src/components/domains/home/More.tsx
  co-kkiri/src/constants/banners.ts
  co-kkiri/src/constants/hotAndNewList.ts
  co-kkiri/src/constants/stackIcons.ts
  co-kkiri/src/layouts/.gitkeep
  co-kkiri/src/lib/mock/mainStudyList.ts
  co-kkiri/src/pages/Home.tsx
Labels: enhancement

#70 Feat: CommentForm 컴포넌트 구현
  co-kkiri/src/components/commons/Button/Button.styled.ts
  co-kkiri/src/components/commons/Button/index.tsx
  co-kkiri/src/components/commons/Comment/index.tsx
  co-kkiri/src/components/commons/CommentForm.tsx
  co-kkiri/src/components/commons/CommentInput.tsx
  co-kkiri/src/components/commons/Textarea/CommentTextarea.tsx
  co-kkiri/src/components/commons/Textarea/Textarea.styled.ts
  co-kkiri/src/components/commons/Textarea/index.tsx
  co-kkiri/src/components/modals/ModalTextarea.tsx
  co-kkiri/src/lib/mock/commentList.ts
Labels: enhancement

#71 Refactor: zustand로 isSideBarOpen 상태 관리 / desktop 사이즈 일때 narrow 사이즈 고려
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/Scrap.tsx
  co-kkiri/src/components/commons/Stack.tsx
  co-kkiri/src/components/domains/home/Banner.tsx
  co-kkiri/src/components/domains/home/Cards.tsx
  co-kkiri/src/hooks/useResponsiveSideBar.ts
  co-kkiri/src/layouts/Navigation.tsx
  co-kkiri/src/lib/mock/mainStudyList.ts
  co-kkiri/src/stores/sideBarStore.ts
Labels: refactor

#78 Feat: OneLinerInput, TextInput 구현
  co-kkiri/src/components/commons/OneLinerInput.tsx
  co-kkiri/src/components/domains/myPage/TextInput.tsx
  co-kkiri/src/constants/textInputRules.ts
Labels: enhancement

#80 Feat: 기술스택 팝오버 구현
  co-kkiri/src/assets/icons/reset.svg
  co-kkiri/src/components/commons/Chips/DefaultChip.tsx
  co-kkiri/src/components/commons/Chips/DeleteStackChip.tsx
  co-kkiri/src/components/commons/Chips/StackChip.tsx
  co-kkiri/src/components/commons/DropDowns/FilterDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/FilterButton.tsx
  co-kkiri/src/components/commons/FilterList.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRow.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailTable.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/index.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/types.ts
  co-kkiri/src/components/commons/Stack.tsx
  co-kkiri/src/components/commons/StackPopover/DeleteStackChipList.tsx
  co-kkiri/src/components/commons/StackPopover/ResetButton.tsx
  co-kkiri/src/components/commons/StackPopover/SelectLayout.tsx
  co-kkiri/src/components/commons/StackPopover/StackChipList.tsx
  co-kkiri/src/components/commons/StackPopover/constants.ts
  co-kkiri/src/components/commons/StackPopover/index.tsx
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/constants/icons.ts
  co-kkiri/src/constants/stackIcons.ts
  co-kkiri/src/constants/stacks.ts
  co-kkiri/src/lib/utils.ts
  co-kkiri/src/styles/tokens.ts
  co-kkiri/src/types/ImageTypes.ts
  co-kkiri/src/types/StackTypes.ts
  co-kkiri/src/utils/ObjectUtils.ts
Labels: enhancement

#82 Feat: 초대응답 모달 UI 구현
  co-kkiri/src/assets/icons/arrow_right_gray.svg
  co-kkiri/src/assets/icons/icon.svg
  co-kkiri/src/components/modals/InviteResponseModal/InviteResponseModal.styled.ts
  co-kkiri/src/components/modals/InviteResponseModal/index.tsx
  co-kkiri/src/components/modals/ModalLayout.tsx
  co-kkiri/src/constants/icons.ts
Labels: enhancement

#84 Refactor: TextFieldInput 리팩토링
  co-kkiri/src/components/commons/OneLinerInput.tsx
  co-kkiri/src/components/domains/myPage/TextInput.tsx
  co-kkiri/src/components/modals/ModalTextFieldInput.tsx
  co-kkiri/src/components/modals/TextFieldInput.tsx
  co-kkiri/src/constants/textInputRules.ts
  co-kkiri/src/styles/tokens.ts
Labels: refactor

#86 Feat: 스터디/프로젝트 목록 페이지 구현
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Category.tsx
  co-kkiri/src/components/commons/Chips/ProjectChip.tsx
  co-kkiri/src/components/commons/DropDowns/SortDropdown.tsx
  co-kkiri/src/components/commons/FilterList.tsx
  co-kkiri/src/components/commons/Pagination_test/StudyListTestPage.tsx
  co-kkiri/src/components/commons/StackPopover/SelectLayout.tsx
  co-kkiri/src/components/domains/studyList/Cards.tsx
  co-kkiri/src/components/domains/studyList/Filters.tsx
  co-kkiri/src/constants/categories.ts
  co-kkiri/src/lib/mock/studyList.ts
  co-kkiri/src/pages/StudyList.tsx
  co-kkiri/src/types/categoryTypes.ts
  co-kkiri/src/utils/getItemsPerPage.ts
Labels: enhancement

#88 Feat: SideBar z index 버그 해결 및 modalLayout 수정
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/commons/SideBar/SideBar.styled.ts
  co-kkiri/src/components/commons/SideBar/SideBarList.tsx
  co-kkiri/src/components/commons/SideBar/index.tsx
  co-kkiri/src/components/modals/AuthModal.tsx
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/components/modals/ModalLayout.tsx
  co-kkiri/src/components/modals/UserProfileModal/index.tsx
  co-kkiri/src/layouts/Navigation.tsx
  co-kkiri/src/styles/reset.ts
  co-kkiri/src/utils/animation.ts
Labels: bug, enhancement

#89 Feat: 평가칩 구현
  co-kkiri/index.html
  co-kkiri/public/fonts/Pretendard-Bold.woff
  co-kkiri/public/fonts/Pretendard-Medium.woff
  co-kkiri/public/fonts/Pretendard-Regular.woff
  co-kkiri/public/fonts/Pretendard-SemiBold.woff
  co-kkiri/src/components/commons/Chips/EvaluationChip.tsx
  co-kkiri/src/components/commons/DropDowns/FilterDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/RecruitDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/SortDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/UserInfoDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/DropMenu.tsx
  co-kkiri/src/constants/evaluationChip.ts
  co-kkiri/src/styles/globals.ts
Labels: enhancement

#92 Fix: 새로고침 시 SideBar 깜빡임 현상 해결
  co-kkiri/src/layouts/Navigation.tsx
Labels: bug

#97 Feat: UserPopover 컴포넌트 구현
  co-kkiri/src/components/commons/Gnb/Gnb.styled.ts
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/components/commons/UserPopover.tsx
  co-kkiri/src/constants/dropDown.ts
  co-kkiri/src/styles/reset.ts
Labels: enhancement

#100 Feat: 드랍 메뉴 버그수정
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/DatePickerWithRange.tsx
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/DeadlineDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/ui/button.tsx
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/ui/calendar.tsx
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/ui/popover.tsx
  co-kkiri/src/components/commons/DropDowns/SortDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/DropMenu.tsx
  co-kkiri/src/components/commons/DropDowns/commons/FilterButton.tsx
Labels: bug

#104 Refactor: more(...) 이미지 DefaultChip 사용해서 나타내기 / 매직넘버 변수로 교체
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/Chips/DefaultChip.tsx
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/commons/Stack.tsx
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/constants/cardChipLimits.ts
Labels: refactor

#107 Feat: DeadlineDropdown 리메이크
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/DatePickerWithRange.tsx
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/DeadlineDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/ui/calendar.tsx
  co-kkiri/src/styles/reset.ts
  co-kkiri/tailwind.config.ts
Labels: enhancement

#108 Chore: navigation 스타일 수정
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/commons/UserPopover.tsx
  co-kkiri/src/layouts/Navigation.tsx
  co-kkiri/src/styles/tokens.ts
Labels: bug

#110 Feat: formatDate 함수, createTimePassedMessage함수 구현
  co-kkiri/src/components/commons/Card/Header.tsx
  co-kkiri/src/components/domains/detail/Comments/Comment.tsx
  co-kkiri/src/components/domains/detail/DetailCard.tsx
  co-kkiri/src/components/domains/detail/RecruitmentPost/index.tsx
  co-kkiri/src/lib/mock/commentList.ts
  co-kkiri/src/lib/mock/studyDetail.ts
  co-kkiri/src/utils/.gitkeep
  co-kkiri/src/utils/formatDate.ts
Labels: enhancement

#115 Fix: prettier 미적용 코드 수정 및 ProjectDetailCard number rendering 추가
  co-kkiri/src/components/commons/Chips/ProjectChip.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRow.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailTable.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/index.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/types.ts
  co-kkiri/src/types/ObjectUtilTypes.ts
Labels: bug

#116 Feat: axios 기본 셋팅
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/axios.ts
Labels: enhancement

#118 Feat: 칩선택드롭다운 구현
  co-kkiri/src/components/commons/Chips/DefaultChip.tsx
  co-kkiri/src/components/commons/DropDowns/StackMultiselectDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/SquareDropButton.tsx
  co-kkiri/src/components/commons/StackPopover/SelectLayout.tsx
Labels: enhancement

#117 Feat: Manage page 레이아웃 구현
  co-kkiri/src/assets/icons/accept.svg
  co-kkiri/src/assets/icons/leader/leader.svg
  co-kkiri/src/assets/icons/leader/leader_background.svg
  co-kkiri/src/assets/icons/reject.svg
  co-kkiri/src/components/commons/ProjectDetailCard/index.tsx
  co-kkiri/src/components/domains/manage/AppliedList.tsx
  co-kkiri/src/components/domains/manage/Buttons.tsx
  co-kkiri/src/components/domains/manage/Detail.tsx
  co-kkiri/src/components/domains/manage/LeaderIcon.tsx
  co-kkiri/src/components/domains/manage/MemberList.tsx
  co-kkiri/src/components/domains/manage/SectionTitle.tsx
  co-kkiri/src/constants/icons.ts
  co-kkiri/src/constants/manageButtons.ts
  co-kkiri/src/lib/mock/manage/appliedMember.ts
  co-kkiri/src/lib/mock/manage/manage.ts
  co-kkiri/src/lib/mock/manage/postTeamMember.ts
  co-kkiri/src/pages/Manage.tsx
  co-kkiri/src/pages/Manage/index.tsx
  co-kkiri/src/pages/Manage/styled.tsx
Labels: enhancement

#120 Feat: apiRequest 함수 구현 및 엔드포인트 별 함수 모듈화
  co-kkiri/src/components/modals/AuthModal.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/auth/index.ts
  co-kkiri/src/lib/api/auth/type.ts
  co-kkiri/src/lib/api/axios.ts
  co-kkiri/src/lib/api/comment/index.ts
  co-kkiri/src/lib/api/comment/type.ts
  co-kkiri/src/lib/api/home/index.ts
  co-kkiri/src/lib/api/home/type.ts
  co-kkiri/src/lib/api/member/index.ts
  co-kkiri/src/lib/api/member/type.ts
  co-kkiri/src/lib/api/myPage/index.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/lib/api/myPost/index.ts
  co-kkiri/src/lib/api/myPost/type.ts
  co-kkiri/src/lib/api/post/index.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/api/teamMember/index.ts
  co-kkiri/src/lib/api/teamMember/type.ts
Labels: enhancement

#122 Feat: Recruit페이지 구현
  co-kkiri/src/PageRouter.tsx
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/DeadlineDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/RecruitDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/DropMenu.tsx
  co-kkiri/src/components/commons/DropDowns/commons/SquareDropButton.tsx
  co-kkiri/src/components/commons/RadioButton.tsx
  co-kkiri/src/components/commons/ReactQuill/CustomToolbar.tsx
  co-kkiri/src/components/commons/ReactQuill/index.tsx
  co-kkiri/src/components/commons/RecruitmentRequestLayout/RecruitLayout.styled.ts
  co-kkiri/src/components/commons/RecruitmentRequestLayout/index.tsx
  co-kkiri/src/components/commons/SelectPositionChipList.tsx
  co-kkiri/src/constants/dropDown.ts
  co-kkiri/src/lib/path.ts
  co-kkiri/src/pages/Casting.tsx
  co-kkiri/src/pages/Post.tsx
  co-kkiri/src/pages/Recruit/index.tsx
  co-kkiri/src/pages/Recruit/styled.ts
  co-kkiri/src/pages/Scout.tsx
  co-kkiri/src/types/recruitmentRequestTypes.ts
Labels: enhancement

#129 Refactor: api 함수 더블 체크 및 주석 추가
  co-kkiri/src/lib/api/axios.ts
  co-kkiri/src/lib/api/comment/index.ts
  co-kkiri/src/lib/api/home/index.ts
  co-kkiri/src/lib/api/member/index.ts
  co-kkiri/src/lib/api/myPage/index.ts
  co-kkiri/src/lib/api/myPost/index.ts
  co-kkiri/src/lib/api/post/index.ts
  co-kkiri/src/lib/api/teamMember/index.ts
Labels: refactor

#130 Feat: 구글 Oauth 기능 구현
  co-kkiri/src/PageRouter.tsx
  co-kkiri/src/components/commons/AuthListener.ts
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/modals/AuthModal.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/auth/index.ts
  co-kkiri/src/lib/api/axios.ts
  co-kkiri/src/lib/path.ts
  co-kkiri/src/pages/Auth/GoogleAuth.tsx
  co-kkiri/src/pages/Profile.tsx
  co-kkiri/src/stores/authModalToggle.ts
  co-kkiri/src/utils/openLoginPopup.ts
Labels: enhancement

#131 Feat: 정보수정모달 구현
  co-kkiri/src/assets/icons/camera.svg
  co-kkiri/src/components/commons/DropDowns/Dropdown.tsx
  co-kkiri/src/components/commons/DropDowns/RecruitDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/UserInfoDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/DropMenu.tsx
  co-kkiri/src/components/commons/DropDowns/commons/SquareDropButton.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/types.ts
  co-kkiri/src/components/commons/Stack.tsx
  co-kkiri/src/components/commons/StackPopover/SelectLayout.tsx
  co-kkiri/src/components/commons/StackPopover/constants.ts
  co-kkiri/src/components/modals/EditUserProfileModal.zip
  co-kkiri/src/components/modals/EditUserProfileModal/EditUserProfileModalLayout.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/FileSelector.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/ModalTextFieldDropdown.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/UserImage.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/index.tsx
  co-kkiri/src/components/modals/ModalLayout.tsx
  co-kkiri/src/components/modals/ModalTextFieldInput.tsx
  co-kkiri/src/components/modals/TextFieldInput.tsx
  co-kkiri/src/constants/icons.ts
  co-kkiri/src/constants/stacks.ts
  co-kkiri/src/constants/textInputRules.ts
  co-kkiri/src/pages/StudyList.tsx
  co-kkiri/src/stores/userInfoStore.ts
  co-kkiri/src/types/ObjectUtilTypes.ts
  co-kkiri/src/types/UserTypes.ts
  co-kkiri/src/utils/ArrayUtils.ts
Labels: enhancement

#136 Feat: 마이페이지 레이아웃 구현
  co-kkiri/src/components/commons/ToggleButton.tsx
  co-kkiri/src/components/domains/manage/SectionTitle.tsx
  co-kkiri/src/components/domains/myPage/InvitedTeamList.tsx
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/components/domains/myPage/TagList.tsx
  co-kkiri/src/components/domains/myPage/UserInfo.tsx
  co-kkiri/src/components/domains/studyList/Filters.tsx
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/lib/mock/myPage/invitedTeam.ts
  co-kkiri/src/lib/mock/myPage/myScrap.ts
  co-kkiri/src/lib/mock/myPage/userProfileInfo.ts
  co-kkiri/src/pages/Manage/styled.ts
  co-kkiri/src/pages/MyPage.tsx
  co-kkiri/src/pages/MyPage/index.tsx
  co-kkiri/src/pages/MyPage/styled.ts
Labels: enhancement

#138 Feat: 유저인포 레이아웃 구현
  co-kkiri/src/components/commons/Chips/PositionChip.tsx
  co-kkiri/src/components/commons/CircularProgressBar.tsx
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.tsx
  co-kkiri/src/components/commons/UserProfileCard/index.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/UserImage.tsx
  co-kkiri/src/types/styledUtilTypes.ts
  co-kkiri/src/utils/styleUtils.ts
Labels: enhancement

#139 Refactor: 닉네임 ModalTextFieldInput에 minLength 조건 추가
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/constants/textInputRules.ts
  co-kkiri/src/styles/tokens.ts
Labels: refactor

#146 Refactor: 변경된 mediaquries에 맞춰서 Positions, Stack 컴포넌트 수정
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/commons/Stacks.tsx
Labels: refactor

#148 Feat: 스카우트페이지 레이아웃 구현
  co-kkiri/src/components/commons/DropDowns/FilterDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/FilterButton.tsx
  co-kkiri/src/components/commons/SearchInput/index.tsx
  co-kkiri/src/components/commons/StackPopover/index.tsx
  co-kkiri/src/components/domains/scout/ScoutCards.tsx
  co-kkiri/src/components/domains/scout/ScoutFilters.tsx
  co-kkiri/src/lib/api/member/type.ts
  co-kkiri/src/lib/mock/scout/searchMemberList.tsx
  co-kkiri/src/pages/Scout.tsx
  co-kkiri/src/pages/Scout/index.tsx
  co-kkiri/src/pages/Scout/styled.tsx
Labels: enhancement

#151 Feat: mystudy 페이지 레이아웃 및 기능 일부 구현
  co-kkiri/src/assets/icons/manage.svg
  co-kkiri/src/assets/icons/pen.svg
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/CardCornerButton.tsx
  co-kkiri/src/components/commons/Scrap.tsx
  co-kkiri/src/components/domains/detail/ShareAndScrap.tsx
  co-kkiri/src/components/domains/studyList/Cards.tsx
  co-kkiri/src/constants/cardCornerButton.ts
  co-kkiri/src/constants/categories.ts
  co-kkiri/src/constants/icons.ts
  co-kkiri/src/lib/mock/myStudy/applied.ts
  co-kkiri/src/lib/mock/myStudy/completed.ts
  co-kkiri/src/lib/mock/myStudy/onGoing.ts
  co-kkiri/src/lib/mock/myStudy/recruiting.ts
  co-kkiri/src/pages/MyStudy.tsx
  co-kkiri/src/stores/myStudyStore.ts
  co-kkiri/src/styles/tokens.ts
  co-kkiri/src/types/categoryTypes.ts
  co-kkiri/src/utils/getCardCornerType.ts
Labels: enhancement

#153 Fix: CircularProgressBar Animation 오류 해결
  co-kkiri/src/components/commons/CircularProgressBar.tsx
Labels: bug

#155 Feat: 스터디관리 api 연결
  co-kkiri/src/PageRouter.tsx
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/domains/manage/AppliedList.tsx
  co-kkiri/src/components/domains/manage/Detail.tsx
  co-kkiri/src/components/domains/manage/MemberList.tsx
  co-kkiri/src/lib/api/axios.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/api/teamMember/index.ts
  co-kkiri/src/lib/api/teamMember/type.ts
  co-kkiri/src/lib/mock/manage/manage.ts
  co-kkiri/src/lib/mock/studyListTest.ts
  co-kkiri/src/pages/Manage/index.tsx
  co-kkiri/src/pages/MyStudy.tsx
  co-kkiri/src/pages/StudyList.tsx
Labels: enhancement

#159 Refector: isScraped 타입 변경 및 자잘한 오류 수정
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/CardCornerButton.tsx
  co-kkiri/src/components/domains/detail/ShareAndScrap.tsx
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/components/domains/scout/ScoutCards.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/EditUserProfileModalLayout.tsx
  co-kkiri/src/constants/cardCornerButton.ts
  co-kkiri/src/lib/api/home/type.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/mock/mainStudyList.ts
  co-kkiri/src/lib/mock/myPage/myScrap.ts
  co-kkiri/src/lib/mock/myStudy/applied.ts
  co-kkiri/src/lib/mock/myStudy/completed.ts
  co-kkiri/src/lib/mock/myStudy/onGoing.ts
  co-kkiri/src/lib/mock/myStudy/recruiting.ts
  co-kkiri/src/lib/mock/studyDetail.ts
  co-kkiri/src/lib/mock/studyList.ts
  co-kkiri/src/lib/mock/studyListTest.ts
  co-kkiri/src/pages/Detail/index.tsx
Labels: refactor

#164 Refactor: mystudy 페이지 자잘한 수정 및 mock 데이터 type 오류 해결
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/CardCornerButton.tsx
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/constants/cardChipLimits.ts
  co-kkiri/src/constants/categories.ts
  co-kkiri/src/lib/mock/mainStudyList.ts
  co-kkiri/src/lib/mock/myStudy/applied.ts
  co-kkiri/src/lib/mock/myStudy/completed.ts
  co-kkiri/src/lib/mock/myStudy/onGoing.ts
  co-kkiri/src/lib/mock/myStudy/recruiting.ts
  co-kkiri/src/pages/Home.tsx
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/MyStudy/styled.ts
  co-kkiri/src/styles/globals.ts
  co-kkiri/src/types/pagesTypes.ts
  co-kkiri/src/utils/getCardCornerType.ts
  co-kkiri/src/utils/getPositionChipLimit.ts
Labels: refactor

#163 Chore: manage 리액트쿼리 적용, UserInfo 모달 연결, myPage 리팩토링
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.styled.tsx
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.tsx
  co-kkiri/src/components/commons/UserProfileCard/index.tsx
  co-kkiri/src/components/domains/manage/AppliedList.tsx
  co-kkiri/src/components/domains/manage/Detail.tsx
  co-kkiri/src/components/domains/manage/MemberList.tsx
  co-kkiri/src/components/domains/myPage/UserInfo.tsx
  co-kkiri/src/components/domains/scout/ScoutCards.tsx
  co-kkiri/src/components/modals/UserProfileModal.tsx
  co-kkiri/src/components/modals/UserProfileModal_invalid/UserProfileModal.styled.ts
  co-kkiri/src/components/modals/UserProfileModal_invalid/index.tsx
  co-kkiri/src/components/modals/UserProfileModal_invalid/test.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/mock/myPage/myScrap.ts
  co-kkiri/src/lib/mock/myPage/userProfileInfo.ts
  co-kkiri/src/pages/Manage/index.tsx
Labels: enhancement, refactor

#162 Refactor: Link 컴포넌트 구현 및 프로젝트 상세 정보 요약 카드 컴포넌트 Stack 부분 코드 대체
  co-kkiri/src/assets/icons/link.svg
  co-kkiri/src/components/commons/Link.tsx
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRow.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/index.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/types.ts
  co-kkiri/src/components/domains/detail/DetailCard.tsx
  co-kkiri/src/constants/icons.ts
Labels: refactor

#171 Feat: 마이페이지 api 연결
  co-kkiri/src/components/domains/myPage/InvitedTeamList.tsx
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/components/domains/myPage/UserInfo.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/myPage/index.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/pages/Manage/index.tsx
  co-kkiri/src/pages/MyPage/index.tsx
Labels: enhancement

#174 Feat: Detail페이지 스터디상세api 연결 및 postApplyStatus 에 따른 버튼 맵핑 구현
  co-kkiri/src/components/commons/Gnb/Gnb.styled.ts
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/components/domains/detail/Comments/index.tsx
  co-kkiri/src/components/domains/detail/DetailCard.tsx
  co-kkiri/src/components/domains/detail/MappedButton.tsx
  co-kkiri/src/components/domains/detail/RecruitmentPost/RecruitmentPost.styled.ts
  co-kkiri/src/components/domains/detail/RecruitmentPost/index.tsx
  co-kkiri/src/components/domains/detail/StatusBasedButton.tsx
  co-kkiri/src/components/modals/AuthModal.tsx
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/components/modals/InviteResponseModal/InviteResponseModal.styled.ts
  co-kkiri/src/components/modals/InviteResponseModal/index.tsx
  co-kkiri/src/components/modals/ModalLayout.tsx
  co-kkiri/src/constants/statusButtonConfig.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/mock/studyDetail.ts
  co-kkiri/src/pages/Detail/index.tsx
  co-kkiri/src/pages/Detail/styled.tsx
Labels: enhancement

#175 Feat: /member/info/summary API 연결
  co-kkiri/src/components/commons/AuthListener.ts
  co-kkiri/src/components/commons/Gnb/GnbUserInfo.tsx
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/auth/index.ts
  co-kkiri/src/lib/api/auth/type.ts
  co-kkiri/src/stores/userInfoStore.ts
Labels: enhancement

#176 Refactor: mystudy 페이지 스타일 변경 반영
  co-kkiri/src/pages/MyStudy/styled.ts
Labels: refactor

#179 Chore: 오류가 나는 fetchUserInfo 함수 하나 삭제
  co-kkiri/src/components/commons/Gnb/index.tsx
Labels: refactor

#181 Refactor: 유저 정보를 가져오는 api를 /member/info/summary에서 /my-page/info로 바꿈
  co-kkiri/src/stores/userInfoStore.ts
Labels: refactor

#186 Feat: NotFound 페이지 구현
  co-kkiri/src/assets/images/logo_animation.svg
  co-kkiri/src/constants/images.ts
  co-kkiri/src/pages/NotFound.tsx
Labels: enhancement

#188 Feat: Detail 페이지 api 연결 및 useCommentMutation, usePostMutation 훅 구현
  co-kkiri/src/components/domains/detail/Comments/Comment.styled.ts
  co-kkiri/src/components/domains/detail/Comments/Comment.tsx
  co-kkiri/src/components/domains/detail/Comments/CommentForm.tsx
  co-kkiri/src/components/domains/detail/Comments/index.tsx
  co-kkiri/src/components/domains/detail/PostManagementButtons.tsx
  co-kkiri/src/components/domains/detail/RecruitmentPost/index.tsx
  co-kkiri/src/components/domains/detail/StatusBasedButton.tsx
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/hooks/useMutation/useCommentMutation.ts
  co-kkiri/src/hooks/useMutation/usePostMutation.ts
  co-kkiri/src/lib/api/comment/index.ts
  co-kkiri/src/lib/api/comment/type.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/pages/Detail/index.tsx
Labels: enhancement

#187 Fix: 프로젝트 상세 요약 카드 연락 방식을 ContactWay와 link 값에 따라 구분
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRow.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/index.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/types.ts
  co-kkiri/src/components/domains/detail/DetailCard.tsx
  co-kkiri/src/utils/validationUtils.ts
Labels: bug

#184 Feat: StudyList API 연결 1차
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/commons/Pagination/index.tsx
  co-kkiri/src/components/commons/Pagination/styled.ts
  co-kkiri/src/components/commons/Pagination_test/Pagination.tsx
  co-kkiri/src/layouts/Navigation.tsx
  co-kkiri/src/lib/api/member/type.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/lib/api/pageMetaType.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/api/teamMember/type.ts
  co-kkiri/src/pages/Scout/index.tsx
  co-kkiri/src/pages/StudyList.tsx
  co-kkiri/src/pages/StudyList/index.tsx
  co-kkiri/src/pages/StudyList/styled.ts
  co-kkiri/src/stores/studyListStore.ts
  co-kkiri/src/utils/getItemsPerPage.ts
Labels: enhancement

#189 Feat: home page, scrap API 연결
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/CardCornerButton.tsx
  co-kkiri/src/components/commons/Positions.tsx
  co-kkiri/src/components/domains/detail/ShareAndScrap.tsx
  co-kkiri/src/components/domains/home/HotAndNewSection.tsx
  co-kkiri/src/constants/cardChipLimits.ts
  co-kkiri/src/constants/cardCornerButton.ts
  co-kkiri/src/constants/hotAndNewList.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/home/type.ts
  co-kkiri/src/lib/api/scrap/index.ts
  co-kkiri/src/lib/mock/mainStudyList.ts
  co-kkiri/src/pages/Detail/index.tsx
  co-kkiri/src/pages/Home.tsx
  co-kkiri/src/types/homeCardListTypes.ts
Labels: enhancement

#190 Feat: FormElement 로직 구현 & 유저 스카우트 후 초대 모달
  co-kkiri/src/components/commons/DropDowns/Dropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/DropMenu.tsx
  co-kkiri/src/components/commons/DropDowns/commons/SquareDropButton.tsx
  co-kkiri/src/components/commons/Form/FormDropdown.tsx
  co-kkiri/src/components/commons/Form/FormElement.tsx
  co-kkiri/src/components/commons/Form/FormTextarea.tsx
  co-kkiri/src/components/commons/Form/Label.tsx
  co-kkiri/src/components/commons/Form/RHFDropdown.tsx
  co-kkiri/src/components/commons/Form/RHFTextArea.tsx
  co-kkiri/src/components/commons/Textarea/Textarea.styled.ts
  co-kkiri/src/components/commons/Textarea/index.tsx
  co-kkiri/src/components/modals/ScoutModal/ScoutUserProfile.tsx
  co-kkiri/src/components/modals/ScoutModal/index.tsx
  co-kkiri/src/components/modals/ScoutModal/types.ts
  co-kkiri/src/components/modals/ScoutModal/utils.ts
  co-kkiri/src/constants/dropDown.ts
  co-kkiri/src/lib/api/member/type.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/mock/scout/scoutList.ts
Labels: enhancement

#198 Fix: FormElement 적용 및 오류 해결
  co-kkiri/src/components/commons/DropDowns/FilterDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/SortDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/DropMenu.tsx
  co-kkiri/src/components/commons/Form/RHFStackPopover.tsx
  co-kkiri/src/components/commons/RecruitmentRequestLayout/index.tsx
  co-kkiri/src/components/domains/detail/Comments/index.tsx
  co-kkiri/src/components/domains/home/Cards.tsx
  co-kkiri/src/components/domains/home/HotAndNewSection.tsx
  co-kkiri/src/components/domains/scout/ScoutFilters.tsx
  co-kkiri/src/components/domains/studyList/Filters.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/EditUserProfileModalLayout.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/ModalTextFieldDropdown.tsx
  co-kkiri/src/components/modals/TextFieldInput.tsx
  co-kkiri/src/lib/mock/myPage/invitedTeam.ts
  co-kkiri/src/lib/mock/myPage/myScrap.ts
  co-kkiri/src/lib/mock/myPage/userProfileInfo.ts
  co-kkiri/src/lib/mock/studyDetail.ts
  co-kkiri/src/lib/mock/studyListTest.ts
  co-kkiri/src/pages/Detail/index.tsx
  co-kkiri/src/pages/Home.tsx
  co-kkiri/src/stores/userInfoStore.ts
  co-kkiri/src/types/userTypes.ts
Labels: bug

#199 Feat: 사이드바 내 푸터 구현
  co-kkiri/src/components/commons/Footer.tsx
  co-kkiri/src/components/commons/SideBar/SideBar.styled.ts
  co-kkiri/src/components/commons/SideBar/SideBarList.tsx
Labels: enhancement

#201 Refactor: 로딩 시 스크랩 버튼 막기 및 useScrapMutation 훅 제작 등
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Card/Header.tsx
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/CardCornerButton.tsx
  co-kkiri/src/constants/hotAndNewList.ts
  co-kkiri/src/hooks/useMutation/useScrapMutation.ts
Labels: refactor

#203 Feat: 마이페이지 스크랩 무한스크롤 구현
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/commons/Gnb/GnbUserInfo.tsx
  co-kkiri/src/components/commons/NoResultText.tsx
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.tsx
  co-kkiri/src/components/commons/UserProfileCard/index.tsx
  co-kkiri/src/components/domains/myPage/InvitedTeamList.tsx
  co-kkiri/src/components/domains/myPage/ScrapList.styled.ts
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/components/domains/myPage/TagList.tsx
  co-kkiri/src/components/domains/myPage/UserInfo.styled.ts
  co-kkiri/src/components/domains/myPage/UserInfo.tsx
  co-kkiri/src/components/domains/scout/ScoutCards.tsx
  co-kkiri/src/components/modals/UserProfileModal.tsx
  co-kkiri/src/components/modals/UserProfileModal_invalid/UserProfileModal.styled.ts
  co-kkiri/src/components/modals/UserProfileModal_invalid/index.tsx
  co-kkiri/src/components/modals/UserProfileModal_invalid/test.tsx
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/pages/MyPage/index.tsx
  co-kkiri/src/pages/StudyList/index.tsx
  co-kkiri/src/stores/userInfoStore.ts
  co-kkiri/src/styles/globals.ts
Labels: enhancement

#206 Feat: Detail 페이지 댓글 infinite query 구현, 지원하기 취소 api 연결, apiRequest함수 에러처리 리팩토링
  co-kkiri/src/components/domains/detail/Comments/CommentForm.tsx
  co-kkiri/src/components/domains/detail/Comments/index.tsx
  co-kkiri/src/components/domains/detail/StatusBasedButton.tsx
  co-kkiri/src/components/domains/scout/ScoutCards.tsx
  co-kkiri/src/hooks/useMutation/usePostMutation.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/axios.ts
  co-kkiri/src/lib/api/post/index.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/pages/Detail/index.tsx
  co-kkiri/src/pages/Scout/styled.tsx
Labels: enhancement

#208 Feat: 스터디관리 버튼 기능 구현
  co-kkiri/src/PageRouter.tsx
  co-kkiri/src/assets/icons/leader.svg
  co-kkiri/src/components/domains/manage/Buttons.tsx
  co-kkiri/src/components/domains/manage/MemberList.tsx
  co-kkiri/src/constants/icons.ts
  co-kkiri/src/constants/manageButtons.ts
  co-kkiri/src/hooks/useManageButtons.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/post/index.ts
  co-kkiri/src/pages/Manage/index.tsx
Labels: enhancement

#209 Feat: review 페이지 EvaluationPart 구현 및 테스트
  co-kkiri/src/components/domains/review/EvaluationPart.tsx
  co-kkiri/src/components/domains/review/RHFEvaluationPart.tsx
  co-kkiri/src/constants/evaluationChip.ts
  co-kkiri/src/pages/Review.tsx
Labels: enhancement

#216 Chore : Detail 페이지 데이터 형식 변경 반영 및 gcTime 셋팅
  co-kkiri/src/components/domains/detail/StatusBasedButton.tsx
  co-kkiri/src/components/modals/InviteResponseModal/index.tsx
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/pages/Detail/index.tsx
Labels: refactor

#213 Fix: 스터디관리 페이지 오류
  co-kkiri/src/components/domains/manage/AppliedList.tsx
  co-kkiri/src/components/domains/manage/Detail.tsx
  co-kkiri/src/hooks/useManageButtons.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/pages/Manage/index.tsx
Labels: bug

#217 Fix: list, detail 페이지에서 scrap 오류 고침
  co-kkiri/src/hooks/useMutation/useScrapMutation.ts
  co-kkiri/src/pages/StudyList/index.tsx
Labels: refactor

#220 Feat: 토스트 구현
  co-kkiri/index.html
  co-kkiri/src/App.tsx
  co-kkiri/src/assets/icons/toastIcons/error.svg
  co-kkiri/src/assets/icons/toastIcons/info.svg
  co-kkiri/src/assets/icons/toastIcons/success.svg
  co-kkiri/src/assets/icons/toastIcons/warn.svg
  co-kkiri/src/components/commons/Widgets/Toast/ToastPortal.tsx
  co-kkiri/src/components/commons/Widgets/Toast/constant.ts
  co-kkiri/src/components/commons/Widgets/Toast/index.tsx
  co-kkiri/src/components/commons/Widgets/Toast/util.ts
  co-kkiri/src/constants/icons.ts
  co-kkiri/src/hooks/useToast.ts
  co-kkiri/src/stores/toastStore.ts
  co-kkiri/src/utils/animation.ts
Labels: enhancement

#223 Feat: StudyList 필터 API 연결
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/commons/SearchInput/index.tsx
  co-kkiri/src/components/domains/studyList/Filters.tsx
  co-kkiri/src/constants/dropDown.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/pages/StudyList/index.tsx
  co-kkiri/src/pages/StudyList/styled.ts
Labels: enhancement

#224 Feat: mystudy 페이지 api 연결
  co-kkiri/src/App.tsx
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/domains/detail/Comments/index.tsx
  co-kkiri/src/components/domains/home/HotAndNewSection.tsx
  co-kkiri/src/components/modals/ScoutModal/index.tsx
  co-kkiri/src/lib/api/myPost/index.ts
  co-kkiri/src/lib/api/myPost/type.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/mock/myStudy/applied.ts
  co-kkiri/src/lib/mock/myStudy/completed.ts
  co-kkiri/src/lib/mock/myStudy/onGoing.ts
  co-kkiri/src/lib/mock/myStudy/recruiting.ts
  co-kkiri/src/pages/Detail/index.tsx
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/MyStudy/styled.ts
  co-kkiri/src/utils/myStudyPageFetchList.ts
Labels: enhancement

#233 Fix: MyPage 수정
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/components/domains/myPage/UserInfo.tsx
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/components/modals/InviteResponseModal/index.tsx
  co-kkiri/src/constants/modal.ts
  co-kkiri/src/pages/MyPage/index.tsx
Labels: bug

#237 Fix: useToast 훅, 단순 구독으로 변환
  co-kkiri/src/hooks/useToast.ts
Labels: bug

#239 Feat: edit user profile modal api연결
  co-kkiri/src/components/commons/DropDowns/StackMultiselectDropdown.tsx
  co-kkiri/src/components/commons/Form/FormElement.tsx
  co-kkiri/src/components/commons/Form/FormStackMultiSelectDropdown.tsx
  co-kkiri/src/components/commons/Form/RHFStackMultiSelectDropdown.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/EditUserProfileModalForm.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/EditUserProfileModalLayout.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/FileSelector.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/RHFEditableUserImage.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/index.tsx
  co-kkiri/src/hooks/useMutation/useImageMutation.ts
  co-kkiri/src/hooks/useMutation/useUserInfoMutation.ts
  co-kkiri/src/lib/api/image/index.ts
  co-kkiri/src/lib/api/image/type.ts
  co-kkiri/src/lib/api/post/index.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/utils/validationUtils.ts
Labels: bug, enhancement

#248 Feat: MyPage 내가 받은 태그 기능 구현, UserInfo 모달 오류 수정
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/components/domains/myPage/TagList.tsx
  co-kkiri/src/components/modals/UserProfileModal.tsx
  co-kkiri/src/lib/mock/mypage/review.ts
Labels: bug

#247 Feat: 초대 모달 api 연결
  co-kkiri/src/components/domains/scout/ScoutCard.tsx
  co-kkiri/src/components/modals/ScoutModal/index.tsx
  co-kkiri/src/components/modals/ScoutModal/types.ts
  co-kkiri/src/components/modals/ScoutModal/utils.ts
  co-kkiri/src/components/modals/UserProfileModal.tsx
  co-kkiri/src/hooks/useMutation/useScoutMutation.ts
  co-kkiri/src/hooks/useToast.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/member/type.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/api/scout/index.ts
  co-kkiri/src/lib/api/scout/type.ts
  co-kkiri/src/types/PositionTypes.ts
Labels: enhancement

#252 Feat: studyList 페이지 필터 zustand 관리 및 home 더보기 기능 구현
  co-kkiri/src/components/commons/Chips/ProjectChip.tsx
  co-kkiri/src/components/commons/DropDowns/FilterDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/SortDropdown.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/index.tsx
  co-kkiri/src/components/commons/RecruitmentRequestLayout/utils.ts
  co-kkiri/src/components/commons/SideBar/SideBarList.tsx
  co-kkiri/src/components/commons/UserPopover.tsx
  co-kkiri/src/components/domains/home/Banner.tsx
  co-kkiri/src/components/domains/home/Banners.tsx
  co-kkiri/src/components/domains/home/HotAndNewSection.tsx
  co-kkiri/src/components/domains/home/More.tsx
  co-kkiri/src/components/domains/studyList/Filters.tsx
  co-kkiri/src/constants/banners.ts
  co-kkiri/src/constants/categoriesAndFilters.ts
  co-kkiri/src/constants/dropDown.ts
  co-kkiri/src/constants/hotAndNewList.ts
  co-kkiri/src/hooks/useFilterSetting.ts
  co-kkiri/src/lib/api/home/type.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/lib/api/myPost/type.ts
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/lib/mock/manage/manage.ts
  co-kkiri/src/lib/mock/studyList.ts
  co-kkiri/src/pages/Home.tsx
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/StudyList/index.tsx
  co-kkiri/src/stores/myStudyStore.ts
  co-kkiri/src/stores/studyListStore.ts
  co-kkiri/src/types/categoryAndFilterTypes.ts
  co-kkiri/src/types/categoryTypes.ts
  co-kkiri/src/types/recruitmentRequestTypes.ts
Labels: enhancement
