Repository co-KKIRI/FE_co-KKIRI, pull requests merged in 2024-04, with the labels that each got.

#256 Feat: 조회수 증가 api 연결
  co-kkiri/src/components/commons/AuthListener.ts
  co-kkiri/src/components/domains/detail/Comments/Comment.tsx
  co-kkiri/src/components/domains/detail/Comments/CommentForm.tsx
  co-kkiri/src/components/domains/detail/StatusBasedButton.tsx
  co-kkiri/src/hooks/useMutation/usePostMutation.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/post/index.ts
  co-kkiri/src/pages/Detail/index.tsx
Labels: enhancement, refactor

#257 Feat: 초대 모달창 api 연결
  co-kkiri/src/components/commons/DropDowns/Dropdown.tsx
  co-kkiri/src/components/modals/InviteResponseModal/index.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/teamMember/index.ts
  co-kkiri/src/lib/api/teamMember/type.ts
Labels: enhancement

#258 Feat: review page 관련 컴포넌트 구현
  co-kkiri/src/assets/icons/checked.svg
  co-kkiri/src/assets/icons/number_1.svg
  co-kkiri/src/assets/icons/number_2.svg
  co-kkiri/src/assets/icons/unchecked.svg
  co-kkiri/src/components/commons/UserInfo.tsx
  co-kkiri/src/components/domains/review/EvaluationPart.tsx
  co-kkiri/src/components/domains/review/MemberEvaluation.tsx
  co-kkiri/src/components/domains/review/MemberReview.tsx
  co-kkiri/src/components/domains/review/SelectMember.tsx
  co-kkiri/src/components/domains/review/StudyEvaluation.tsx
  co-kkiri/src/components/modals/UserProfileModal.tsx
  co-kkiri/src/constants/evaluationChip.ts
  co-kkiri/src/constants/icons.ts
  co-kkiri/src/lib/mock/review/members.ts
  co-kkiri/src/pages/Review.tsx
  co-kkiri/src/pages/Review/index.tsx
  co-kkiri/src/pages/Review/styled.ts
Labels: enhancement

#259 Refactor: myPage 레이아웃 및 api 일부 수정 / list 페이지 zustand 수정
  co-kkiri/src/components/commons/Card/index.tsx
  co-kkiri/src/lib/api/post/type.ts
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/MyStudy/styled.ts
  co-kkiri/src/pages/StudyList/index.tsx
Labels: refactor

#271 Refactor: 스크랩 오류 해결 및 gcTime 삭제
  co-kkiri/src/components/commons/CardCornerButton.tsx
  co-kkiri/src/hooks/useMutation/useScrapMutation.ts
  co-kkiri/src/pages/Detail/index.tsx
  co-kkiri/src/pages/Home.tsx
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/StudyList/index.tsx
Labels: refactor

#273 Fix: IOS -> iOS 및 career null 문제 해결
  co-kkiri/src/components/commons/SelectPositionChipList.tsx
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.tsx
  co-kkiri/src/components/commons/UserProfileCard/constants.ts
  co-kkiri/src/constants/dropDown.ts
  co-kkiri/src/lib/mock/manage/manage.ts
  co-kkiri/src/lib/mock/studyList.ts
Labels: bug

#275 Feat:모집글 작성,수정 및 초대 응답모달 토스트 추가, 접근제한 설정
  co-kkiri/src/components/commons/RecruitmentRequestLayout/index.tsx
  co-kkiri/src/components/commons/RecruitmentRequestLayout/utils.ts
  co-kkiri/src/components/modals/InviteResponseModal/index.tsx
  co-kkiri/src/pages/Edit.tsx
  co-kkiri/src/pages/Recruit/index.tsx
Labels: enhancement

#278 Feat: home 배너 이미지 구현 및 파비콘 설정, 토스트 기능 구현
  co-kkiri/index.html
  co-kkiri/src/assets/icons/favicon.svg
  co-kkiri/src/assets/images/homeBannerImages/recruit_desktop_narrow.svg
  co-kkiri/src/assets/images/homeBannerImages/recruit_desktop_wide.svg
  co-kkiri/src/assets/images/homeBannerImages/recruit_mobile.svg
  co-kkiri/src/assets/images/homeBannerImages/recruit_tablet.svg
  co-kkiri/src/assets/images/homeBannerImages/scout_desktop_narrow.svg
  co-kkiri/src/assets/images/homeBannerImages/scout_desktop_wide.svg
  co-kkiri/src/assets/images/homeBannerImages/scout_mobile.svg
  co-kkiri/src/assets/images/homeBannerImages/scout_tablet.svg
  co-kkiri/src/assets/images/homeBannerImages/studyList_desktop_narrow.svg
  co-kkiri/src/assets/images/homeBannerImages/studyList_desktop_wide.svg
  co-kkiri/src/assets/images/homeBannerImages/studyList_mobile.svg
  co-kkiri/src/assets/images/homeBannerImages/studyList_tablet.svg
  co-kkiri/src/components/domains/home/Banner.tsx
  co-kkiri/src/constants/banners.ts
  co-kkiri/src/constants/images.ts
  co-kkiri/src/constants/toast.ts
  co-kkiri/src/hooks/useMutation/useScrapMutation.ts
  co-kkiri/src/pages/MyStudy/index.tsx
Labels: enhancement

#280 Fix: UserProfile stack과 stacks 모두 받도록 수정 및 Query 수정
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.tsx
  co-kkiri/src/components/modals/UserProfileModal.tsx
  co-kkiri/src/lib/api/myPage/type.ts
Labels: bug

#281 Fix: manage page 버그
  co-kkiri/src/components/commons/Chips/PositionChip.tsx
  co-kkiri/src/components/domains/manage/AppliedList.tsx
  co-kkiri/src/components/domains/manage/Buttons.tsx
  co-kkiri/src/components/domains/manage/ManageButton.tsx
  co-kkiri/src/components/domains/manage/MemberList.tsx
  co-kkiri/src/constants/manageButtons.ts
  co-kkiri/src/hooks/useManageButtons.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/post/index.ts
  co-kkiri/src/lib/api/teamMember/type.ts
  co-kkiri/src/pages/Manage/index.tsx
Labels: bug

#283 Design: 캘린더 사이즈 확대
  co-kkiri/src/components/commons/DropDowns/DeadlineDropdown/DeadlineDropdown.tsx
Labels: enhancement

#284 Feat: myPage 내가 받은 태그 기능 구현
  co-kkiri/src/components/commons/Chips/DefaultChip.tsx
  co-kkiri/src/components/commons/Chips/EvaluationChip.tsx
  co-kkiri/src/components/domains/myPage/MyPageUserInfo.styled.ts
  co-kkiri/src/components/domains/myPage/MyPageUserInfo.tsx
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/components/domains/myPage/TagList.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/myPage/index.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/lib/mock/mypage/review.ts
  co-kkiri/src/pages/MyPage/index.tsx
  co-kkiri/src/styles/reset.ts
Labels: enhancement

#287 Fix: project detail card 버그 해결
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRow.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRowContent.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRowContents/Capacity.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRowContents/ContactWay.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRowContents/Text.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/types.ts
  co-kkiri/src/components/commons/Stacks.tsx
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.tsx
  co-kkiri/src/constants/dropDown.ts
  co-kkiri/src/utils/objectUtils.ts
Labels: bug

#289 Feat: studylist, scout 페이지 에러 토스트 추가
  co-kkiri/src/pages/Scout/index.tsx
  co-kkiri/src/pages/StudyList/index.tsx
Labels: enhancement

#290 Feat: 스켈레톤 구현
  co-kkiri/src/components/commons/Card/Card.styled.ts
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/commons/Skeleton/CardsSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/DetailCardSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/HomeCardsSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/ScoutCardsSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/ScrapListSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/TextSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/UserInfoCardSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/UserProfileSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/elements/CardSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/elements/DefaultSkeleton.ts
  co-kkiri/src/components/commons/Skeleton/elements/StacksSkeleton.tsx
  co-kkiri/src/components/domains/home/Cards.tsx
  co-kkiri/src/components/domains/scout/ScoutCards.tsx
  co-kkiri/src/pages/Scout/styled.tsx
Labels: enhancement

#291 Refactor: mystudy 페이지 대기중 목록 추가
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/constants/categoriesAndFilters.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/myPost/index.ts
  co-kkiri/src/lib/api/myPost/type.ts
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/MyStudy/styled.ts
  co-kkiri/src/types/categoryAndFilterTypes.ts
  co-kkiri/src/utils/getCardCornerType.ts
  co-kkiri/src/utils/myStudyPageFetchList.ts
Labels: refactor

#294 Feat: ReactQuill 이미지 업로드 기능 구현
  co-kkiri/src/components/commons/ReactQuill/index.tsx
Labels: enhancement

#295 Refactor: 프로필 수정 모달 링크 정규식 변경/ 로그인 시 사이드바에 나의 스터디, 마이 페이지 뜨게 함/ 토스트 추가
  co-kkiri/src/components/commons/SideBar/SideBarList.tsx
  co-kkiri/src/constants/textInputRules.ts
  co-kkiri/src/layouts/Navigation.tsx
  co-kkiri/src/pages/Home.tsx
Labels: refactor

#296 Feat: Detail page 스켈레톤 적용 및 useHandleError 훅 구현
  co-kkiri/src/components/commons/Skeleton/DetailCardSkeleton.tsx
  co-kkiri/src/components/commons/Skeleton/TextSkeleton.tsx
  co-kkiri/src/components/domains/detail/Comments/Comment.tsx
  co-kkiri/src/components/domains/detail/Comments/CommentForm.tsx
  co-kkiri/src/components/domains/detail/Comments/index.tsx
  co-kkiri/src/components/domains/detail/DetailCard.tsx
  co-kkiri/src/components/domains/detail/RecruitmentPost/index.tsx
  co-kkiri/src/components/domains/detail/StatusBasedButton.tsx
  co-kkiri/src/constants/toast.ts
  co-kkiri/src/hooks/useHandleError.ts
  co-kkiri/src/lib/initialData/detail.ts
  co-kkiri/src/pages/Detail/index.tsx
Labels: enhancement, refactor

#297 Feat: 스켈레톤 UI 적용하기
  co-kkiri/src/components/commons/Cards.tsx
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/domains/home/HotAndNewSection.tsx
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/pages/Home.tsx
  co-kkiri/src/pages/Manage/index.tsx
  co-kkiri/src/pages/MyPage/index.tsx
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/Scout/index.tsx
  co-kkiri/src/pages/StudyList/index.tsx
Labels: enhancement

#301 Feat: 상세페이지 버튼 스켈레톤 적용
  co-kkiri/src/components/commons/Skeleton/ButtonSkeleton.tsx
  co-kkiri/src/components/domains/detail/StatusBasedButton.tsx
  co-kkiri/src/pages/Detail/index.tsx
Labels: enhancement, refactor

#303 Feat: useSkeleton 구현
  co-kkiri/src/hooks/useSkeleton.ts
Labels: enhancement

#300 Refactor: Detail 페이지 useQuery error핸들러 추가 , Recruit 로그인 안한 유저 글작성에러에 네이게이트 제거, StacksCardsSkeleton 디자인 수정
  co-kkiri/src/components/commons/Skeleton/ScoutCardsSkeleton.tsx
  co-kkiri/src/hooks/useHandleError.ts
  co-kkiri/src/pages/Detail/index.tsx
  co-kkiri/src/pages/Recruit/index.tsx
Labels: refactor

#302 fix: 모달 창 열림 시 화면의 최상단으로 이동되는 현상 고침
  co-kkiri/src/components/modals/ModalLayout.tsx
  co-kkiri/src/utils/handleScrollForModal.ts
Labels: refactor

#304 Feat: 페이지 이동 시 상단으로 이동하는 기능 구현
  co-kkiri/src/PageRouter.tsx
  co-kkiri/src/components/commons/FloatingButton/ScrollToTop.tsx
  co-kkiri/src/components/commons/PageScrollTop.ts
Labels: enhancement

#306 Fix: dropdown의 크기가 무한정으로 길어지는 문제
  co-kkiri/src/components/commons/DropDowns/commons/DropMenu.tsx
  co-kkiri/src/styles/globals.ts
Labels: bug

#308 Fix: 허용 여부에 따라 모달 외부 클릭시 닫히도록 설정
  co-kkiri/src/components/commons/SideBar/index.tsx
  co-kkiri/src/components/domains/review/ReviewModal/index.tsx
  co-kkiri/src/components/modals/AuthModal.tsx
  co-kkiri/src/components/modals/ConfirmModal.tsx
  co-kkiri/src/components/modals/InviteResponseModal/index.tsx
  co-kkiri/src/components/modals/ModalLayout.tsx
  co-kkiri/src/components/modals/ScoutModal/index.tsx
  co-kkiri/src/components/modals/UserProfileModal.tsx
Labels: bug

#309 Feat: 스켈레톤 UI 적용 관련 컴포넌트 수정 및 useSkeleton훅 적용
  co-kkiri/src/components/commons/Gnb/index.tsx
  co-kkiri/src/components/domains/home/HotAndNewSection.tsx
  co-kkiri/src/components/domains/manage/AppliedList.tsx
  co-kkiri/src/components/domains/manage/Detail.tsx
  co-kkiri/src/components/domains/manage/MemberList.tsx
  co-kkiri/src/components/domains/myPage/InvitedTeamList.tsx
  co-kkiri/src/components/domains/myPage/ScrapList.tsx
  co-kkiri/src/pages/Manage/index.tsx
  co-kkiri/src/pages/Manage/styled.ts
  co-kkiri/src/pages/MyPage/index.tsx
  co-kkiri/src/pages/MyStudy/index.tsx
  co-kkiri/src/pages/Scout/index.tsx
  co-kkiri/src/pages/StudyList/index.tsx
Labels: enhancement

#310 Fix: 스켈레톤이 끝나고 실제 데이터가 반영된 카드의 높이를 측정하도록 변경
  co-kkiri/src/hooks/useComponentHeight.ts
  co-kkiri/src/pages/Detail/index.tsx
Labels: bug

#311 Fix: recruit에서 기본값이 두개씩 보이는 버그 해결
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRow.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRowContents/Capacity.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRowContents/ContactWay.tsx
  co-kkiri/src/constants/dropDown.ts
Labels: bug

#312 Feat: 리뷰페이지 api 연결
  co-kkiri/src/components/domains/manage/MemberList.tsx
  co-kkiri/src/components/domains/review/EvaluationPart.tsx
  co-kkiri/src/components/domains/review/MemberEvaluation.tsx
  co-kkiri/src/components/domains/review/MemberReview.tsx
  co-kkiri/src/components/domains/review/RHFEvaluationPart.tsx
  co-kkiri/src/components/domains/review/SelectMember.tsx
  co-kkiri/src/components/domains/review/StudyEvaluation.tsx
  co-kkiri/src/constants/evaluationChip.ts
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/myPost/index.ts
  co-kkiri/src/lib/api/review/index.ts
  co-kkiri/src/lib/api/review/type.ts
  co-kkiri/src/pages/Review/index.tsx
  co-kkiri/src/pages/StudyList/index.tsx
  co-kkiri/src/stores/reviewStore.ts
Labels: enhancement, 살려주세요

#319 Refactor: 피그마 변경된 시안 반영 및 페이지네이션 수정
  co-kkiri/src/components/commons/Pagination/index.tsx
  co-kkiri/src/components/commons/Pagination/styled.ts
  co-kkiri/src/components/commons/SideBar/SideBar.styled.ts
  co-kkiri/src/layouts/Navigation.tsx
Labels: refactor

#321 Feat: 스켈레톤 위치 수정
  co-kkiri/src/pages/StudyList/index.tsx
  co-kkiri/src/pages/StudyList/styled.tsx
Labels: enhancement

#323 Fix: popover portal 설정, 및 실시간 Trigger Ref위 위치 계산으로 동적 위치 변화
  co-kkiri/index.html
  co-kkiri/src/components/commons/DropDowns/StackMultiselectDropdown.tsx
  co-kkiri/src/components/commons/ProjectDetailCard/ProjectDetailRowContents/ContactWay.tsx
  co-kkiri/src/components/commons/StackPopover/SelectLayout.tsx
  co-kkiri/src/components/commons/StackPopover/index.tsx
  co-kkiri/src/components/commons/Widgets/Popover/PopoverContainer.tsx
  co-kkiri/src/components/commons/Widgets/Popover/PopoverPortal.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/EditUserProfileModalForm.tsx
  co-kkiri/src/components/modals/UserProfileModal.tsx
  co-kkiri/src/hooks/useSkeleton.ts
Labels: bug

#327 Fix: review 페이지 버그, mypage 스타일 수정
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.styled.tsx
  co-kkiri/src/components/domains/myPage/MyPageUserInfo.styled.ts
  co-kkiri/src/components/domains/myPage/MyPageUserInfo.tsx
  co-kkiri/src/components/domains/myPage/TagList.tsx
  co-kkiri/src/pages/MyPage/index.tsx
  co-kkiri/src/pages/Review/index.tsx
Labels: bug

#328 Feat: 리뷰 조회 모달 api 연동
  co-kkiri/src/components/modals/ReviewModal/index.tsx
Labels: enhancement

#334 Refactor: createTimePassedMessage 함수 date-fns 라이브러리 적용
  co-kkiri/src/utils/formatDate.ts
Labels: refactor

#337 Fix: stacksMultiSelect 에서 각 Chip에 X 클릭이 안되는 문제 등등 버그 해결
  co-kkiri/src/components/commons/Chips/DefaultChip.tsx
  co-kkiri/src/components/commons/DropDowns/Dropdown.tsx
  co-kkiri/src/components/commons/DropDowns/StackMultiselectDropdown.tsx
  co-kkiri/src/components/commons/DropDowns/commons/SquareDropButton.tsx
  co-kkiri/src/components/commons/StackPopover/index.tsx
  co-kkiri/src/components/commons/Widgets/Popover/PopoverContainer.tsx
  co-kkiri/src/styles/tokens.ts
Labels: bug

#343 Fix: gauge 못받아오는 문제 해결
  co-kkiri/src/components/commons/CircularProgressBar.tsx
  co-kkiri/src/components/commons/UserProfileCard/UserProfileCardLayout.tsx
  co-kkiri/src/components/commons/UserProfileCard/index.tsx
  co-kkiri/src/components/domains/myPage/MyPageUserInfo.tsx
  co-kkiri/src/components/domains/scout/ScoutCard.tsx
  co-kkiri/src/components/domains/scout/ScoutCards.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/EditUserProfileModalLayout.tsx
  co-kkiri/src/components/modals/EditUserProfileModal/index.tsx
  co-kkiri/src/lib/api/member/type.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/stores/userInfoStore.ts
Labels: bug

#345 Feat: 스카우트 모달 내 태그 API 연결 및 기타 버그 수정
  co-kkiri/src/components/commons/CollapseSection.tsx
  co-kkiri/src/components/domains/myPage/TagList.tsx
  co-kkiri/src/components/modals/UserProfileModal/UserProfileTagList.tsx
  co-kkiri/src/components/modals/UserProfileModal/index.tsx
  co-kkiri/src/lib/api/address.ts
  co-kkiri/src/lib/api/member/index.ts
  co-kkiri/src/lib/api/member/type.ts
  co-kkiri/src/lib/api/myPage/type.ts
  co-kkiri/src/pages/MyPage/index.tsx
  co-kkiri/src/types/tagtypes.ts
Labels: enhancement

#351 Fix: 리뷰모달 중복태그 컴포넌트 수정
  co-kkiri/src/components/commons/Chips/EvaluationChip.tsx
  co-kkiri/src/components/modals/ReviewModal/index.tsx
Labels: bug

#355 Refactor: 사이드바가 나타나고 사라질 때 부드러운 애니메이션 추가
  co-kkiri/src/layouts/Navigation.tsx
Labels: refactor
